/*
 * Copyright 2020-2025 AVSystem <avsystem@avsystem.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * Generated by anjay_codegen.py on 2021-08-02 12:50:18
 *
 * LwM2M Object: Pattern detector
 * ID: 33650, URN: urn:oma:lwm2m:ext:33650, Optional, Multiple
 *
 * This object is used to report the pattern detected by the ML-based
 * classification algorithms and to count the number of times it has been
 * detected.
 */
#ifdef USE_AIBP

#include <assert.h>
#include <stdbool.h>

#include <anjay/anjay.h>
#include <avsystem/commons/avs_defs.h>
#include <avsystem/commons/avs_list.h>
#include <avsystem/commons/avs_memory.h>
#include <avsystem/commons/avs_mutex.h>

#include "ai_bridge.h"

/**
 * Detector State: R, Single, Mandatory
 * type: boolean, range: N/A, unit: N/A
 * The current state of a detector.
 */
#define RID_DETECTOR_STATE 2000

/**
 * Detector Counter: R, Single, Mandatory
 * type: integer, range: N/A, unit: N/A
 * The cumulative value of patterns detected.
 */
#define RID_DETECTOR_COUNTER 2001

/**
 * Pattern Name: R, Single, Mandatory
 * type: string, range: N/A, unit: N/A
 * Name of the pattern being detected.
 */
#define RID_PATTERN_NAME 2002

typedef struct pattern_detector_instance_state_struct {
    bool detector_state;
    int32_t detector_counter;
} pattern_detector_instance_state_t;

typedef struct pattern_detector_instance_struct {
    anjay_iid_t iid;

    pattern_detector_instance_state_t curr_state;
    pattern_detector_instance_state_t cached_state;
    const char *pattern_name;
} pattern_detector_instance_t;

typedef struct pattern_detector_object_struct {
    const anjay_dm_object_def_t *def;
    pattern_detector_instance_t *instances;

    avs_mutex_t *instance_state_mtx;
} pattern_detector_object_t;

static const pattern_detector_instance_state_t INITIAL_STATE = {
    .detector_state = false,
    .detector_counter = 0
};

static pattern_detector_instance_t *
find_instance(const pattern_detector_object_t *obj, anjay_iid_t iid) {
    return iid < ai_bridge_num_of_classes ? &obj->instances[iid] : NULL;
}

static inline pattern_detector_object_t *
get_obj(const anjay_dm_object_def_t *const *obj_ptr) {
    assert(obj_ptr);
    return AVS_CONTAINER_OF(obj_ptr, pattern_detector_object_t, def);
}

static int list_instances(anjay_t *anjay,
                          const anjay_dm_object_def_t *const *obj_ptr,
                          anjay_dm_list_ctx_t *ctx) {
    (void) anjay;

    for (size_t i = 0; i < ai_bridge_num_of_classes; i++) {
        anjay_dm_emit(ctx, i);
    }

    return 0;
}

static int init_instance(pattern_detector_instance_t *inst, anjay_iid_t iid) {
    assert(iid != ANJAY_ID_INVALID);
    assert(iid < ai_bridge_num_of_classes);

    inst->iid = iid;
    inst->curr_state = INITIAL_STATE;
    inst->cached_state = INITIAL_STATE;
    inst->pattern_name = ai_bridge_classes[iid];

    return 0;
}

static pattern_detector_instance_t *add_instance(pattern_detector_object_t *obj,
                                                 anjay_iid_t iid) {
    pattern_detector_instance_t *created = &obj->instances[iid];
    return init_instance(created, iid) ? NULL : created;
}

static int list_resources(anjay_t *anjay,
                          const anjay_dm_object_def_t *const *obj_ptr,
                          anjay_iid_t iid,
                          anjay_dm_resource_list_ctx_t *ctx) {
    (void) anjay;
    (void) obj_ptr;
    (void) iid;

    anjay_dm_emit_res(ctx, RID_DETECTOR_STATE, ANJAY_DM_RES_R,
                      ANJAY_DM_RES_PRESENT);
    anjay_dm_emit_res(ctx, RID_DETECTOR_COUNTER, ANJAY_DM_RES_R,
                      ANJAY_DM_RES_PRESENT);
    anjay_dm_emit_res(ctx, RID_PATTERN_NAME, ANJAY_DM_RES_R,
                      ANJAY_DM_RES_PRESENT);
    return 0;
}

static int resource_read(anjay_t *anjay,
                         const anjay_dm_object_def_t *const *obj_ptr,
                         anjay_iid_t iid,
                         anjay_rid_t rid,
                         anjay_riid_t riid,
                         anjay_output_ctx_t *ctx) {
    (void) anjay;

    pattern_detector_object_t *obj = get_obj(obj_ptr);
    assert(obj);
    pattern_detector_instance_t *inst = find_instance(obj, iid);
    assert(inst);

    /*
     * Implementation is lock-free as it was assumed that:
     * 1) reading the object state is atomic and
     * 2) the conditional statements are not used in the function.
     */

    switch (rid) {
    case RID_DETECTOR_STATE:
        assert(riid == ANJAY_ID_INVALID);
        return anjay_ret_bool(ctx, inst->cached_state.detector_state);

    case RID_DETECTOR_COUNTER:
        assert(riid == ANJAY_ID_INVALID);
        return anjay_ret_i32(ctx, inst->cached_state.detector_counter);

    case RID_PATTERN_NAME:
        assert(riid == ANJAY_ID_INVALID);
        return anjay_ret_string(ctx, inst->pattern_name);

    default:
        return ANJAY_ERR_METHOD_NOT_ALLOWED;
    }
}

static const anjay_dm_object_def_t OBJ_DEF = {
    .oid = 33650,
    .handlers = {
        .list_instances = list_instances,

        .list_resources = list_resources,
        .resource_read = resource_read,
    }
};

const anjay_dm_object_def_t **pattern_detector_object_create(void) {
    pattern_detector_object_t *obj = (pattern_detector_object_t *) avs_calloc(
            1, sizeof(pattern_detector_object_t));
    if (!obj) {
        return NULL;
    }
    obj->def = &OBJ_DEF;

    avs_mutex_create(&obj->instance_state_mtx);

    obj->instances = (pattern_detector_instance_t *) avs_calloc(
            ai_bridge_num_of_classes, sizeof(pattern_detector_instance_t));
    if (!obj->instances) {
        return NULL;
    }

    for (size_t i = 0; i < ai_bridge_num_of_classes; i++) {
        if (!add_instance(obj, i)) {
            return NULL;
        }
    }

    return &obj->def;
}

static const anjay_dm_object_def_t **OBJ_DEF_PTR;

int pattern_detector_object_install(anjay_t *anjay) {
    OBJ_DEF_PTR = pattern_detector_object_create();
    return anjay_register_object(anjay, OBJ_DEF_PTR);
}

void pattern_detector_object_update(anjay_t *anjay) {
    if (!OBJ_DEF_PTR) {
        return;
    }

    pattern_detector_object_t *obj = get_obj(OBJ_DEF_PTR);

    for (size_t i = 0; i < ai_bridge_num_of_classes; i++) {
        pattern_detector_instance_t *it = &obj->instances[i];

        avs_mutex_lock(obj->instance_state_mtx);

        if (it->cached_state.detector_state != it->curr_state.detector_state) {
            it->cached_state.detector_state = it->curr_state.detector_state;
            anjay_notify_changed(anjay, obj->def->oid, i, RID_DETECTOR_STATE);
        }

        if (it->cached_state.detector_counter
                != it->curr_state.detector_counter) {
            it->cached_state.detector_counter = it->curr_state.detector_counter;
            anjay_notify_changed(anjay, obj->def->oid, i, RID_DETECTOR_COUNTER);
        }

        avs_mutex_unlock(obj->instance_state_mtx);
    }
}

void pattern_detector_object_value_update(int detected_class) {
    pattern_detector_object_t *obj = get_obj(OBJ_DEF_PTR);

    for (size_t i = 0; i < ai_bridge_num_of_classes; i++) {
        pattern_detector_instance_t *it = &obj->instances[i];

        avs_mutex_lock(obj->instance_state_mtx);

        if (it->iid == detected_class) {
            it->curr_state.detector_state = true;
            it->curr_state.detector_counter++;
        } else {
            it->curr_state.detector_state = false;
        }

        avs_mutex_unlock(obj->instance_state_mtx);
    }
}

#endif
